include!("runtime/contracts.rs");
include!("runtime/channels.rs");
include!("runtime/entrypoint.rs");
include!("runtime/lifecycle.rs");
include!("runtime/graceful_tests.rs");
include!("runtime/supervisor_ack.rs");
include!("runtime/scope_release.rs");
include!("runtime/ack_tests.rs");
include!("runtime/binding_runtime_tests.rs");
