include!("daemon_replacement/fixtures.rs");
include!("daemon_replacement/daemon_fixture.rs");
include!("daemon_replacement/startup_recovery.rs");
include!("daemon_replacement/quarantine.rs");
include!("daemon_replacement/quarantine_assertions.rs");
include!("daemon_replacement/owner_change.rs");
include!("daemon_replacement/dbus_owner_change.rs");
include!("daemon_replacement/owner_change_assertions.rs");
include!("daemon_replacement/conflicts_and_processes.rs");
