struct PamSessionLaunch<'a, F, I, G, C, L>
where
    F: WorkerAuthenticatorFactory,
    I: UnixIdentityResolver,
    G: SupplementaryGroupsResolver,
    C: SessionChildRunnerFactory,
    L: LogindSessionResolver,
{
    factory: &'a F,
    identity_resolver: &'a I,
    supplementary_groups_resolver: &'a G,
    session_child_runner_factory: &'a C,
    logind_resolver: &'a L,
    request: niralis_session::SessionRequest,
    connection: Option<niralis_session::LoginRequestBinding>,
    pam_service: String,
    password: niralis_session::WorkerSecret,
    session_child_path: std::path::PathBuf,
    session_probe_path: std::path::PathBuf,
    control_path: std::path::PathBuf,
    worker_id: String,
    launcher_pid: u32,
    virtual_terminal_allocator: &'a dyn VirtualTerminalAllocator,
    runtime_dir_validator: &'a dyn RuntimeDirValidator,
    selinux_context_manager: &'a dyn SelinuxContextManager,
    payload_scope_manager: &'a dyn crate::payload_scope::PayloadScopeManager,
    launch_phase_gate: &'a dyn LaunchPhaseGate,
    launch_plan: niralis_session::SessionExecPlan,
    login_identity: niralis_session::WorkerTransactionIdentity,
}

fn run_pam_session<
    W: Write,
    F: WorkerAuthenticatorFactory,
    I: UnixIdentityResolver,
    G: SupplementaryGroupsResolver,
    C: SessionChildRunnerFactory,
    L: LogindSessionResolver,
>(
    writer: &mut W,
    launch: PamSessionLaunch<'_, F, I, G, C, L>,
) -> Result<(), SessionError> {
    let PamSessionLaunch {
        factory,
        identity_resolver,
        supplementary_groups_resolver,
        session_child_runner_factory,
        logind_resolver,
        request,
        connection,
        pam_service,
        password,
        session_child_path,
        session_probe_path,
        control_path,
        worker_id,
        launcher_pid,
        virtual_terminal_allocator,
        runtime_dir_validator,
        selinux_context_manager,
        payload_scope_manager,
        launch_phase_gate,
        launch_plan,
        mut login_identity,
    } = launch;
    include!("pam_session/pre_open.rs")
}
